"$schema" = 'https://starship.rs/config-schema.json'

add_newline = true

[character]
success_symbol = "[~>](bold green)"
error_symbol = "[~>](bold red) "

[package]
disabled = true

[nodejs]
symbol = 'ğŸ€ '

[cmake]
symbol = 'ğŸ”º '

[conda]
symbol = 'ğŸ§ª '

[gradle]
symbol = 'ğŸ˜ '

[directory]
truncate_to_repo = false
truncation_length = 0
